sudo: required

services:
  - docker

before_install:
  - docker images

script:
  - docker build ./tomcat-8-openjdk -t jiangz/tomcat:8.0-openjdk

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    set -e;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jiangz/tomcat:8.0-openjdk;
    docker logout;
    fi

